name: DungeonsPlugin
version: '1.0.0'
main: com.mmhs.dungeons.DungeonsPlugin
api-version: '1.21'
author: MMHS
description: A Minecraft Paper plugin for dungeons

commands:
  dungeon:
    description: Manage dungeons
    usage: /dungeon <create|addspawn|start|stop|list> [args]
    permission: dungeons.use
    aliases: [dg, dun]
  ditems:
    description: Gives dungeon weapons, test command
    usage: /ditems
    permission: op

permissions:
  dungeons.use:
    description: Allows use of dungeon commands
    default: op

