name: MMHSDungeons
main: com.mmhs.dungeons.core.DungeonsPlugin
version: 1.1
api-version: 1.21
authors:
  - mmhs

commands:
  dungeon:
    description: Manage simple dungeons
    usage: /dungeon <create|addspawn|start|stop|list>
    permission: dungeons.use
  ditems:
    description: Gives dungeon weapons
    usage: /ditems
    permission: dungeons.admin

permissions:
  dungeons.use:
    description: Allows using the dungeon command
    default: op
  dungeons.admin:
    description: Allows using /ditems
    default: op
